version: '3'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 9090:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: password
        volumes:
            - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
